slug = "hulkSmash"
title = "Just Smash!"
author = "Henry"
value = 50
description = """Just smash through the stack!"""
tags = [ "buffer" ]
files = [ "hulkSmash" ]
flag = "flag{B4BY_IT'S_Z00M3R_T1M3}"
enabled = false
