slug = "finally-awake"
title = "You're Finally Awake"
author = "Game Studio"
value = 0
description = "You were trying to cross the border, right? Walked right into that green wall over there... Remember, the flag format is flag{flagContentHere}. Flags present themselves on the main menu after you have completed the level by touching the red square. All 3 challenges are based on the same [game](https://www.dropbox.com/s/hzl486h30xa5xyo/Final%20Cyber%20Game.7z?dl=1)."
tags = [ "game" ]
files = []
flag = "flag{cheaters_never_win?}"
enabled = true
