slug = "powell-cat"
title = "Powell Cat"
author = "Yunfan"
value = 200
description = "Is [powell cat](powell) a switch? That might be the case. Submit the return value wrapped in `flag{}`!"
tags = [ "assembly" ]
files = [ "powell" ]
flag = "flag{5}"
enabled = true
