title = "ACM Cyber"
home = """
# Spring Quarter Workshops
Hey everyone, welcome to Cyber's online challenge platform! Although most of us aren't on campus, that doesn't mean the workshops have to stop. This quarter's focus is on binary executables &ndash; the files your source code compiles into. This type of file contains primitive instructions that a computer **actually** follows, so it's important to understand how they work. We've divided the content into four weekly workshops, each described below.

So how will these workshops work? Before anything else, join our [Discord](https://discord.gg/j9dgf2q). We'll be recording video sessions every week to teach and work through examples. And as always, there'll be more challenges for you to practice with here!"""
