slug = "jumpman"
title = "Jumpman"
author = "Game Studio"
value = 0
description = "What are you UP to? Remember, the flag format is flag{flagContentHere}. Flags present themselves on the main menu after you have completed the level by touching the red square. All 3 challenges are based on the same [game](CyberGame.rar)."
tags = [ "game" ]
files = [ "CyberGame.rar" ]
flag = "flag{finished_this_fight}"
enabled = true
