slug = "just-smash"
title = "Just Smash!"
author = "Henry"
value = 30
description = "Just [smash](hulkSmash) through the stack!"
tags = [ "buffer" ]
files = [ "hulkSmash" ]
flag = "flag{B4BY_IT'S_Z00M3R_T1M3}"
enabled = true
