slug = "open-says-me"
title = "Open Says Me"
author = "Yunfan"
value = 40
description = "You've found a mysterious [code segment](sesame.cpp). Can you find a string that will make it return true? Submit the string wrapped in `flag{}`!"
tags = [ "source" ]
files = [ "sesame.cpp" ]
flag = "flag{sl0aaell}"
enabled = true
