slug = "week-3-feedback"
title = "Week 3 Feedback"
author = "Aarin"
value = 10
description = "As always, we appreciate any [feedback]() you have!"
tags = [ "feedback" ]
files = []
flag = ""
enabled = false
