slug = "week-3-feedback"
title = "Week 3 Feedback"
author = "Aarin"
value = 10
description = "As always, we appreciate any feedback you have! (Form is closed now, sorry)"
tags = [ "feedback" ]
files = []
flag = "flag{when_you_undo_something_you_are_reversing_engineering}"
enabled = false
