slug = "for-the-love-of-counting"
title = "For the Love of Counting"
author = "Yunfan"
value = 35
description = "Trace through this for-loop and tell me what this returns. Count carefully!"
tags = [ "dynamic" ]
files = [ "count" ]
flag = "flag{37}"
enabled = true
