slug = "week-4-feedback"
title = "Week 4 Feedback"
author = "defund"
value = 10
description = "As always, we appreciate any [feedback](https://forms.gle/dSssYFivc3d63dJf8) you have!"
tags = [ "feedback" ]
files = []
flag = "flag{tougher_buffer}"
enabled = true
