slug = "gamemode-3"
title = "Gamemode 3"
author = "Game Studio"
value = 0
description = "You're not invisible, you're just looking in the wrong place. Remember, the flag format is flag{flagContentHere}. Flags present themselves on the main menu after you have completed the level by touching the red square. All 3 challenges are based on the same [game](https://www.dropbox.com/s/hzl486h30xa5xyo/Final%20Cyber%20Game.7z?dl=1)."
tags = [ "game" ]
files = []
flag = "flag{do_a_barrel_roll}"
enabled = true
