slug = "treasureMap"
title = "Treasure!"
author = "Henry"
value = 20
description = """ARGGG, Ye matey got a treasure map. Where are the treasure stored?"""
tags = [ "buffer" ]
files = [ "treasureMap" ]
flag = "flag{y0u_ar3_r3ady_t0_del1ver_mai1}"
enabled = false