slug = "hungry"
title = "Hungry"
author = "ellie"
value = 40
description = """Hey I stole this [program](hungry) from my nemesis, Mr. Lobster! It's supposed to have the secrets his amazing 5 course meals. Find the flag so I can dominate muahahahaha!

Be sure to format the flag as flag{what_you_found_as_the_flag}"""
tags = [ "dynamic" ]
files = [ "hungry" ]
flag = "flag{bolah_Soarwilean}"
enabled = false
