slug = "week-2-feedback"
title = "Week 2 Feedback"
author = "Ted"
value = 10
description = "Gimme the feedback, boss. (Form is closed now, sorry)"
tags = [ "feedback" ]
files = []
flag = "flag{when_you_undo_something_you_are_reversing_engineering}"
enabled = true
